sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 
  - 14
branches:
  only:
    - master
notifications:
  email: false
script:
  - yarn start
after_success:
  - yarn report-coverage
